# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asset.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'asset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from miliastra_agent.core.proto_gen import camera_pb2 as camera__pb2
from miliastra_agent.core.proto_gen import entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61sset.proto\x12\x0egame.gia.asset\x1a\x0c\x65ntity.proto\x1a\x0c\x63\x61mera.proto\"\xd2\x03\n\x05\x41sset\x12\'\n\x04meta\x18\x01 \x01(\x0b\x32\x19.game.gia.asset.AssetMeta\x12\x33\n\x10\x64\x65pendent_assets\x18\x02 \x03(\x0b\x32\x19.game.gia.asset.AssetMeta\x12\x0c\n\x04name\x18\x03 \x01(\t\x12-\n\x04type\x18\x05 \x01(\x0e\x32\x1f.game.gia.asset.Asset.AssetType\x12\x34\n\x0b\x65ntity_data\x18\x0c \x01(\x0b\x32\x1d.game.gia.asset.entity.EntityH\x00\x12\x36\n\rcamera_config\x18\x11 \x01(\x0b\x32\x1d.game.gia.camera.CameraConfigH\x00\"\xb6\x01\n\tAssetType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x45NTITY\x10\x03\x12\x0b\n\x07TERRAIN\x10\x05\x12\x13\n\x0fPLAYER_TEMPLATE\x10\x12\x12\x17\n\x13PROFESSION_TEMPLATE\x10\x11\x12\n\n\x06\x43\x41MERA\x10\r\x12\n\n\x06LAYOUT\x10\x14\x12\x10\n\x0cPRESET_POINT\x10\x06\x12\x0c\n\x08UNIT_TAG\x10,\x12\x1d\n\x19\x45NVIRONMENT_CONFIGURATION\x10\x31\x42\x07\n\x05value\"\x9a\x02\n\tAssetMeta\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\x05\x12:\n\tmeta_type\x18\x03 \x01(\x0e\x32\'.game.gia.asset.AssetMeta.AssetMetaType\x12\x10\n\x08\x61sset_id\x18\x04 \x01(\x05\"\xad\x01\n\rAssetMetaType\x12\n\n\x06\x43\x41MERA\x10\x00\x12\n\n\x06\x45NTITY\x10\x02\x12\x0b\n\x07TERRAIN\x10\x05\x12\x13\n\x0fPLAYER_TEMPLATE\x10\x01\x12\x17\n\x13PROFESSION_TEMPLATE\x10\x03\x12\n\n\x06LAYOUT\x10\x08\x12\x10\n\x0cPRESET_POINT\x10\t\x12\x0c\n\x08UNIT_TAG\x10\x17\x12\x1d\n\x19\x45NVIRONMENT_CONFIGURATION\x10\x31\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSET']._serialized_start=60
  _globals['_ASSET']._serialized_end=526
  _globals['_ASSET_ASSETTYPE']._serialized_start=335
  _globals['_ASSET_ASSETTYPE']._serialized_end=517
  _globals['_ASSETMETA']._serialized_start=529
  _globals['_ASSETMETA']._serialized_end=811
  _globals['_ASSETMETA_ASSETMETATYPE']._serialized_start=638
  _globals['_ASSETMETA_ASSETMETATYPE']._serialized_end=811
# @@protoc_insertion_point(module_scope)
