# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mera.proto\x12\x0fgame.gia.camera\"E\n\x0c\x43\x61meraConfig\x12\x35\n\x0e\x63\x61mera_details\x18\x01 \x03(\x0b\x32\x1d.game.gia.camera.CameraDetail\"S\n\x0c\x43\x61meraDetail\x12\x11\n\tcamera_id\x18\x01 \x01(\r\x12\x30\n\x0b\x63\x61mera_data\x18\x02 \x01(\x0b\x32\x1b.game.gia.camera.CameraData\"\x95\x03\n\nCameraData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65\x66\x61ult_distance\x18\x02 \x01(\x02\x12\x15\n\rfield_of_view\x18\x03 \x01(\x02\x12:\n\x10viewpoint_offset\x18\x04 \x01(\x0b\x32 .game.gia.camera.ViewpointOffset\x12\x14\n\x0cmin_distance\x18\x05 \x01(\x02\x12\x14\n\x0cmax_distance\x18\x06 \x01(\x02\x12\x13\n\x0b\x63\x61mera_mode\x18\x0c \x01(\r\x12\x17\n\x0f\x66ollow_rotation\x18\r \x01(\x08\x12\x10\n\x08\x66ield_14\x18\x0e \x01(\x02\x12\x1c\n\x14min_horizontal_angle\x18\x0f \x01(\x02\x12\x1c\n\x14max_horizontal_angle\x18\x10 \x01(\x02\x12\x17\n\x0fmin_pitch_angle\x18\x11 \x01(\x02\x12\x17\n\x0fmax_pitch_angle\x18\x12 \x01(\x02\x12\x18\n\x10ignore_collision\x18\x13 \x01(\x02\x12\x18\n\x10horizontal_angle\x18\x14 \x01(\x02\"2\n\x0fViewpointOffset\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERACONFIG']._serialized_start=33
  _globals['_CAMERACONFIG']._serialized_end=102
  _globals['_CAMERADETAIL']._serialized_start=104
  _globals['_CAMERADETAIL']._serialized_end=187
  _globals['_CAMERADATA']._serialized_start=190
  _globals['_CAMERADATA']._serialized_end=595
  _globals['_VIEWPOINTOFFSET']._serialized_start=597
  _globals['_VIEWPOINTOFFSET']._serialized_end=647
# @@protoc_insertion_point(module_scope)
