# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gia.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'gia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from miliastra_agent.core.proto_gen import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgia.proto\x12\x08game.gia\x1a\x0b\x61sset.proto\"6\n\rGIACollection\x12%\n\x06\x41ssets\x18\x01 \x03(\x0b\x32\x15.game.gia.asset.Assetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GIACOLLECTION']._serialized_start=36
  _globals['_GIACOLLECTION']._serialized_end=90
# @@protoc_insertion_point(module_scope)
